version: "3"

services:
  sparcs-newbie-mongo:
    image: mongo:4.2
    container_name: sparcs-newbie-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:27017
    volumes:
      - sparcs-newbie-postgres-data:/var/lib/postgresql/data

volumes:
  sparcs-newbie-postgres-data:
